### ISSUE TITLE
Uncaught ArgumentCountError: Too few arguments to function Music::getYoutube()

### ISSUE THREAD

**Issue by FDiskas** [jodacame/youtube-music-engine#10]
```html
<b>Fatal error</b>:  Uncaught ArgumentCountError: Too few arguments to function Music::getYoutube(), 0 passed in /var/www/html/system/core/CodeIgniter.php on line 359 and exactly 2 expected in /var/www/html/application/modules/music/controllers/music.php:857
Stack trace:
#0 /var/www/html/system/core/CodeIgniter.php(359): Music-&gt;getYoutube()
#1 /var/www/html/index.php(208): require_once('/var/www/html/s...')
#2 {main}
  thrown in <b>/var/www/html/application/modules/music/controllers/music.php</b> on line <b>857</b><br />
```

**Comment by FDiskas** [comment]
It happens then I tried to search or listen.
php:7.1

**Comment by faceplayit** [comment]
Not really sure if this will help but make sure your php.ini file matches the php version you are running.

**Comment by FDiskas** [comment]
https://github.com/jodacame/youtube-music-engine/blob/84652f3b0df76ae53b0323a889459fad758f01c3/application/modules/music/controllers/music.php#L562
Removed the argument and it worked.
Made an pull request. Sorry about reformating the code :clock3:
